- name: Create WireGuard config directory
  file:
    path: /opt/wireguard
    state: directory
    mode: '0755'

- name: Assign Internal IP (10.66.0.1) to host on eth0
  command: ip addr add 10.66.0.1/24 dev eth0
  ignore_errors: true

- name: Ensure internal IP persists after reboot
  lineinfile:
    path: /etc/network/interfaces
    line: |
      auto eth0:1
      iface eth0:1 inet static
          address 10.66.0.1
          netmask 255.255.255.0
    create: yes
  when: ansible_os_family == "Debian"

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: Set up NAT for VPN traffic
  command: iptables -t nat -A POSTROUTING -s 10.66.0.0/24 -o eth0 -j MASQUERADE

- name: Save iptables rules
  shell: iptables-save > /etc/iptables.rules

- name: Ensure iptables rules persist on reboot
  lineinfile:
    path: /etc/rc.local
    line: "iptables-restore < /etc/iptables.rules"
    create: yes
    mode: '0755'

- name: Deploy WireGuard container
  community.docker.docker_container:
    name: wireguard
    image: "linuxserver/wireguard"
    state: started
    restart_policy: always
    network_mode: host
    privileged: yes
    volumes:
      - /opt/wireguard:/config
      - /lib/modules:/lib/modules
    env:
      PUID: "1000"
      PGID: "1000"
      SERVERPORT: "51820"
      SERVERURL: "{{ ansible_ssh_host }}"
      PEERS: "1"
      PEERDNS: "1.1.1.1"
      INTERNAL_SUBNET: "10.66.0.0/24"
      ALLOWEDIPS: "10.66.0.0/24"
      TZ: "Europe/London"

- name: Enable WireGuard kernel module
  shell: "modprobe wireguard"
  changed_when: false
  notify: Restart Docker
