- name: Deploy Nginx Proxy Manager
  docker_container:
    name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    state: started
    restart_policy: always
    networks:
      - name: proxy-network
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /data/nginx:/data
      - /data/letsencrypt:/etc/letsencrypt