- name: Install Docker
  apt:
    name: docker.io
    state: present
- name: Add user to docker group
  user:
    name: admin
    groups: docker
    append: yes

- name: Create Portainer data volume
  docker_volume:
    name: portainer_data

- name: Deploy Portainer container
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    state: started
    restart_policy: always
    ports:
      - "9443:9443"  # Web UI
      - "8000:8000"  # Edge Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data