- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Configure Docker to not modify iptables
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "iptables": false
      }
    mode: '0644'
  notify: Restart Docker

- name: Add user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes

- name: Create Docker network for Reverse Proxying
  community.docker.docker_network:
    name: proxy-network
    driver: bridge

- name: Create Portainer data volume
  docker_volume:
    name: portainer_data

- name: Deploy Portainer container
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    state: started
    restart_policy: always
    networks:
      - name: proxy-network
    ports:
      - "9443:9443"  # Web UI
      - "8000:8000"  # Edge Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data