- name: Set up UFW - Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Set up UFW -  Allow HTTP 
  ufw:
    rule: allow
    port: "80"
    proto: tcp


- name: Set up UFW - Allow Nginx Proxy Manager from WG Network
  ufw:
    rule: allow
    port: "81"
    proto: tcp
    from_ip: "10.66.0.0/24"

- name: Set up UFW -  Allow HTTPS
  ufw: 
    rule: allow
    port: "443"
    proto: tcp

- name: Set up UFW -  Allow Zabbix
  ufw: 
    rule: allow
    port: "10050"
    proto: tcp

- name: Set up UFW - Allow WireGuard VPN
  ufw:
    rule: allow
    port: "51820"
    proto: udp

- name: Set up UFW - Allow Protainer from WG Network
  ufw:
    rule: allow
    port: "9443"
    proto: tcp
    from_ip: "10.66.0.0/24"

- name: Set up UFW - Allow Nginx Proxy Manager to host
  ufw:
    rule: allow
    proto: tcp
    from_ip: "172.18.0.0/16"
    to_ip: "10.66.0.0/24"

- name: Enable UFW
  ufw:
    state: enabled

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'